[project]
name = "meevoo-backend"
version = "0.1.0"
description = "review everything. a forloop project."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-ninja>=1.3.0",
    "django>=5.1.4",
]
